create table datarequest(
 	 id bigint  generated by default as identity ,
	 submitUser char(7),
	 submitDate date,
	 content varchar(1024),
	 status int,
	  wjd int,
	  difficulty int,
	  doUser char(7),
	  doDate Date,
	  resultString varchar(1024)

)
